version: '3.8'

services:
  postgres-database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kimbo
      - POSTGRES_PASSWORD=pass1234
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: